2023-12-09 01:34:08 - fighter_details [ERROR] Failed to create scraper object
Traceback (most recent call last):
  File "/home/woitek/repos/mma_project/ufcstats_scraper/ufcstats_scraper/scrapers/fighter_details.py", line 373, in scrape_fighter
    scraper = FighterDetailsScraper.model_validate(data_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/woitek/.local/share/virtualenvs/ufcstats_scraper-XKVCaO-Q/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for FighterDetailsScraper
link
  Value error, link has invalid host [type=value_error, input_value='http://ufcstats.com/figh...etails/a1f6999fe57236e0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error
